name: Linting and Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Lint
        run: make lint

  doc-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run Doc Tests
        run: make test-doc

  docs-api-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Install rustdoc-md
        run: cargo install rustdoc-md
      - name: Generate API docs
        run: make docs-api
      - name: Check for uncommitted changes
        run: git diff --exit-code docs/API.md

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run Unit Tests
        run: make test-unit

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    environment: tests
    env:
      TEST_SEED_1: ${{ secrets.TEST_SEED_1 }}
      TEST_SEED_2: ${{ secrets.TEST_SEED_2 }}
      TEST_SEED_3: ${{ secrets.TEST_SEED_3 }}
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Fund Test Accounts
        run: |
          python -m pip install --upgrade pip
          pip install xrpl-py
          python scripts/fund_test_accounts.py
      - name: Run Integration Tests
        run: make test-integration
